"""empty message

Revision ID: 0c381c1da497
Revises: 74a5c55b2749
Create Date: 2021-10-07 10:29:33.589127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c381c1da497'
down_revision = '74a5c55b2749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('payment_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'payment_status')
    # ### end Alembic commands ###
