"""empty message

Revision ID: 1b46cc4ff9e5
Revises: 416ca529225e
Create Date: 2021-12-19 08:58:46.083193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b46cc4ff9e5'
down_revision = '416ca529225e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('manual_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'manual_score')
    # ### end Alembic commands ###
