"""empty message

Revision ID: 1b6d152bfba9
Revises: f1bcce63c56c
Create Date: 2021-06-26 08:49:32.112447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6d152bfba9'
down_revision = 'f1bcce63c56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('prize_pool', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'prize_pool')
    # ### end Alembic commands ###
