"""empty message

Revision ID: 2a26c53be4de
Revises: cca1be337528
Create Date: 2021-10-07 10:12:23.013258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a26c53be4de'
down_revision = 'cca1be337528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('payment_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'payment_id')
    # ### end Alembic commands ###
