"""empty message

Revision ID: 30c242d4d232
Revises: b25cc7d8f95f
Create Date: 2021-12-23 14:14:58.706331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c242d4d232'
down_revision = 'b25cc7d8f95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('team', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('team', sa.Column('timezone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'timezone')
    op.drop_column('team', 'start_time')
    op.drop_column('team', 'start_date')
    # ### end Alembic commands ###
