"""empty message

Revision ID: 30eebad6312e
Revises: 3ee26bf4abdb
Create Date: 2021-12-26 11:46:14.975417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30eebad6312e'
down_revision = '3ee26bf4abdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'start_datetime')
    op.add_column('team', sa.Column('start_datetime', sa.DateTime(), nullable=True))
    op.drop_column('team', 'start_date')
    op.drop_column('team', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('start_time', sa.DATETIME(), nullable=True))
    op.add_column('team', sa.Column('start_date', sa.DATETIME(), nullable=True))
    op.drop_column('team', 'start_datetime')
    op.add_column('event', sa.Column('start_datetime', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
