"""empty message

Revision ID: 3ec9297438f2
Revises: bf41f1cf061f
Create Date: 2021-09-18 09:59:58.102350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec9297438f2'
down_revision = 'bf41f1cf061f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('mode', sa.String(length=50), nullable=True))
    with op.batch_alter_table('event') as event_op:
        event_op.drop_column('team_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('team_size', sa.INTEGER(), nullable=True))
    op.drop_column('event', 'mode')
    # ### end Alembic commands ###
