"""empty message

Revision ID: 3ee26bf4abdb
Revises: 13350d1242ac
Create Date: 2021-12-26 11:45:16.127133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee26bf4abdb'
down_revision = '13350d1242ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'end_time')
    # ### end Alembic commands ###
