"""empty message

Revision ID: 416ca529225e
Revises: 0c381c1da497
Create Date: 2021-11-29 12:04:36.534315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416ca529225e'
down_revision = '0c381c1da497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('flexible_start_ind', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('flexible_start_time_length', sa.Integer(), nullable=True))
    op.drop_column('team', 'payment_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('payment_status', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('event', 'flexible_start_time_length')
    op.drop_column('event', 'flexible_start_ind')
    # ### end Alembic commands ###
