"""empty message

Revision ID: 474d49b31feb
Revises: 68eafece20df
Create Date: 2022-01-19 14:32:10.843501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474d49b31feb'
down_revision = '68eafece20df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('warzone_connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'warzone_connected')
    # ### end Alembic commands ###
