"""empty message

Revision ID: 6b98a01bf680
Revises: 1b6d152bfba9
Create Date: 2021-07-29 18:20:29.613481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b98a01bf680'
down_revision = '1b6d152bfba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('kdr', sa.Float(asdecimal=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'kdr')
    # ### end Alembic commands ###
