"""empty message

Revision ID: 74a5c55b2749
Revises: 2a26c53be4de
Create Date: 2021-10-07 10:26:24.538992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a5c55b2749'
down_revision = '2a26c53be4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('payment_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'payment_complete')
    # ### end Alembic commands ###
