"""empty message

Revision ID: 75db3da7da13
Revises: d159391a043c
Create Date: 2021-12-20 14:30:39.124907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75db3da7da13'
down_revision = 'd159391a043c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('account_type', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'account_type')
    # ### end Alembic commands ###
