"""empty message

Revision ID: 7ca94eb43b79
Revises: 75db3da7da13
Create Date: 2021-12-20 14:32:22.396029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca94eb43b79'
down_revision = '75db3da7da13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('platform', sa.String(length=80), nullable=True))
    op.drop_column('player', 'account_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('account_type', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('player', 'platform')
    # ### end Alembic commands ###
