"""empty message

Revision ID: 8f8afd8095dd
Revises: efaf046a1cf1
Create Date: 2022-01-14 16:05:24.983082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8afd8095dd'
down_revision = 'efaf046a1cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('platform', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('warzone_avatarUrl', sa.String(length=2000), nullable=True))
    op.add_column('user', sa.Column('warzone_player_id', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'warzone_player_id')
    op.drop_column('user', 'warzone_avatarUrl')
    op.drop_column('user', 'username')
    op.drop_column('user', 'platform')
    # ### end Alembic commands ###
