"""empty message

Revision ID: b25cc7d8f95f
Revises: 7ca94eb43b79
Create Date: 2021-12-22 07:59:52.899494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25cc7d8f95f'
down_revision = '7ca94eb43b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('external_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'external_url')
    # ### end Alembic commands ###
