"""empty message

Revision ID: bf41f1cf061f
Revises: 6b98a01bf680
Create Date: 2021-09-12 14:40:55.666795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf41f1cf061f'
down_revision = '6b98a01bf680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('avatarUrl', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'avatarUrl')
    # ### end Alembic commands ###
