"""empty message

Revision ID: d159391a043c
Revises: 1b46cc4ff9e5
Create Date: 2021-12-20 14:04:14.035279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd159391a043c'
down_revision = '1b46cc4ff9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('placement', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'placement')
    # ### end Alembic commands ###
