"""empty message

Revision ID: efaf046a1cf1
Revises: 9de407cb8266
Create Date: 2022-01-14 15:47:01.168456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaf046a1cf1'
down_revision = '9de407cb8266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_accounts', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_accounts', 'email')
    # ### end Alembic commands ###
