"""empty message

Revision ID: f1bcce63c56c
Revises: 8e9096592712
Create Date: 2021-05-04 19:47:43.077221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bcce63c56c'
down_revision = '8e9096592712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('start_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'start_time')
    # ### end Alembic commands ###
