"""empty message

Revision ID: faa2d08180b2
Revises: 30c242d4d232
Create Date: 2021-12-26 11:19:56.677741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa2d08180b2'
down_revision = '30c242d4d232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('start_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'start_datetime')
    # ### end Alembic commands ###
